# Generated by Django 2.2.5 on 2021-04-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exchange_timezone', models.TextField()),
                ('exchange_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('name', models.TextField()),
                ('current_value', models.FloatField()),
                ('ticker', models.TextField(primary_key=True, serialize=False)),
                ('ex_dividend_date', models.DateField(null=True)),
                ('dividend_amount', models.FloatField()),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Value_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Stock')),
            ],
            options={
                'unique_together': {('date', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Histogram_Entry',
            fields=[
                ('median_value', models.FloatField()),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_app.Value_History')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Stock')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Analyst')),
            ],
            options={
                'unique_together': {('title', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Viewed_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Stock')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.User')),
            ],
            options={
                'unique_together': {('date_viewed', 'username', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('date', models.DateField()),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
                ('sentiment', models.SmallIntegerField()),
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Analyst')),
                ('u_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.User')),
            ],
            options={
                'unique_together': {('survey_id', 'u_username')},
            },
        ),
        migrations.CreateModel(
            name='Stock_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Stock')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Analysis')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Analyst')),
            ],
            options={
                'unique_together': {('title', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('strike_price', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('premium', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Stock')),
            ],
            options={
                'unique_together': {('expiry_date', 'strike_price', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('strike_price', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('premium', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Stock')),
            ],
            options={
                'unique_together': {('expiry_date', 'strike_price', 'ticker')},
            },
        ),
    ]
