# Generated by Django 3.1.7 on 2021-03-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('names', models.TextField()),
                ('exchange_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('names', 'exchange_id')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('name', models.TextField()),
                ('current_value', models.FloatField()),
                ('ticker', models.TextField(primary_key=True, serialize=False)),
                ('dividend_date', models.DateField()),
                ('dividend_amount', models.FloatField()),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Value_History',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stock')),
            ],
            options={
                'unique_together': {('date', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('median', models.FloatField()),
                ('quartiles', models.FloatField()),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_app.value_history')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stock')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('strike_price', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('premium', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('strike_price', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('premium', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('description', models.TextField()),
                ('approval', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.analyst')),
            ],
            options={
                'unique_together': {('title', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Viewed_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stock')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
            options={
                'unique_together': {('date_viewed', 'username', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('date', models.DateField()),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
                ('sentiment', models.SmallIntegerField()),
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.analyst')),
                ('u_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
            options={
                'unique_together': {('survey_id', 'u_username')},
            },
        ),
        migrations.CreateModel(
            name='Stock_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.stock')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.analysis')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.analyst')),
            ],
            options={
                'unique_together': {('title', 'username')},
            },
        ),
    ]
