# Generated by Django 2.2.5 on 2021-04-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histogram_entry',
            old_name='median_value',
            new_name='value',
        ),
    ]
