# Generated by Django 2.2.5 on 2021-04-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('expiry_date', 'strike_price', 'ticker')},
        ),
        migrations.AlterUniqueTogether(
            name='put',
            unique_together={('expiry_date', 'strike_price', 'ticker')},
        ),
    ]
