# Generated by Django 2.2.5 on 2021-04-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210414_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='dividend_date',
        ),
        migrations.AddField(
            model_name='stock',
            name='ex_dividend_date',
            field=models.DateField(null=True),
        ),
    ]
