# Generated by Django 2.2.5 on 2021-04-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20210415_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='names',
            new_name='exchange_timezone',
        ),
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set(),
        ),
    ]
