# Generated by Django 3.2 on 2021-04-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_analysis_approval'),
        ('test_app', '0004_auto_20210415_1624'),
    ]

    operations = [
    ]
